version: "3"
services:
  rf-esupdater:
    build: ./rf-esupdater
    container_name: "rf-esupdater"
    environment:
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK_ENV}
      - LOG_PAYLOAD=true
      - AMQP_URL=amqp://guest:guest@rf-crm-rabbitmq:5672
      - LS_CI_LEAD_SINGLE_URL=http://logstash:8081
      - LS_CI_LEAD_MULTI_URL=http://logstash:8082
      - OS_CI_ORDER_SINGLE_URL=http://logstash:8083
      - OS_CI_ORDER_MULTI_URL=http://logstash:8084
      - ES_URL=http://elasticsearch:9200
    volumes:
      - "${SSH_AUTH_SOCK_VOLUME_SRC}:${SSH_AUTH_SOCK_VOLUME_DST}"
      - ${GOPATH}/src/github.com/AlphaFounders/esupdater:/go/src/github.com/AlphaFounders/esupdater
    command: /usr/local/bin/app/entrypoint.sh
    networks:
      - rproxy
    labels:
      - traefik.enable=true
      - baseURL=/esupdater

  rf-car:
    build: ./rf-car
    container_name: "rf-car"
    ports:
      - "8092:8092"
    env_file: ./rf-car/.env.${ENVIRONMENT:-prod}
    environment:
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK_ENV}
    volumes:
      - "${SSH_AUTH_SOCK_VOLUME_SRC}:${SSH_AUTH_SOCK_VOLUME_DST}"
      - ${GOPATH}/src/github.com/AlphaFounders/rf-car:/go/src/github.com/AlphaFounders/rf-car
    command: /usr/local/bin/app/entrypoint.sh
    networks:
      - rproxy
    labels:
      - traefik.enable=true
      - baseURL=/car

  rf-team:
    build: ./rf-team
    container_name: "rf-team"
    ports:
      - "9095:9095"
      - "3003:3003"
    environment:
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK_ENV}
      - LISTEN_ADDRESS=0.0.0.0:3003
      - DB_URL=postgres://postgres:postgres@rf-crm-postgresdb/rf_team?sslmode=disable
      - LISTEN_ADDRESS_HTTP=0.0.0.0:9095
      - TRACE_ENABLE=false
      - DB_TRACE=true
      - LOG_QUERY=true
      - INSURER_SERVICE_ADDRESS=rf-car:2533
    volumes:
      - "${SSH_AUTH_SOCK_VOLUME_SRC}:${SSH_AUTH_SOCK_VOLUME_DST}"
      - ${GOPATH}/src/github.com/AlphaFounders/rf-team:/go/src/github.com/AlphaFounders/rf-team
    command: /usr/local/bin/app/entrypoint.sh
    networks:
      - rproxy
    labels:
      - traefik.enable=true
      - baseURL=/team

  rf-document:
    build: ./rf-document
    container_name: "rf-document"
    ports:
      - "9096:9096"
      - "3004:3004"
    environment:
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK_ENV}
      - LISTEN_ADDRESS=0.0.0.0:3004
      - DB_URL=postgres://postgres:postgres@rf-crm-postgresdb/rf_document?sslmode=disable
      - LISTEN_ADDRESS_HTTP=0.0.0.0:9096
      - TRACE_ENABLE=false
      - DB_TRACE=true
      - LOG_QUERY=true
      - GOOGLE_APPLICATION_CREDENTIALS=./sa-key.json
      - GOOGLE_STORAGE_BUCKET=focused-arch
    volumes:
      - "${SSH_AUTH_SOCK_VOLUME_SRC}:${SSH_AUTH_SOCK_VOLUME_DST}"
      - ${GOPATH}/src/github.com/AlphaFounders/rf-document:/go/src/github.com/AlphaFounders/rf-document
    command: /usr/local/bin/app/entrypoint.sh
    networks:
      - rproxy
    labels:
      - traefik.enable=true
      - baseURL=/document

  rf-user:
    build: ./rf-user
    container_name: "rf-user"
    ports:
      - "9097:9097"
      - "3006:3006"
    environment:
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK_ENV}
      - LISTEN_ADDRESS=0.0.0.0:3006
      - DB_URL=postgres://postgres:postgres@rf-crm-postgresdb/rf_user?sslmode=disable
      - LISTEN_ADDRESS_HTTP=0.0.0.0:9097
      - TRACE_ENABLE=false
      - DB_TRACE=true
      - LOG_QUERY=true
      - LOG_PAYLOAD=true
      - KRATOS_URL=127.0.0.1:4434
    volumes:
      - "${SSH_AUTH_SOCK_VOLUME_SRC}:${SSH_AUTH_SOCK_VOLUME_DST}"
      - ${GOPATH}/src/github.com/AlphaFounders/rf-user:/go/src/github.com/AlphaFounders/rf-user
    command: /usr/local/bin/app/entrypoint.sh
    networks:
      - rproxy
    labels:
      - traefik.enable=true
      - baseURL=/user

  rf-calendar:
    build: ./rf-calendar
    container_name: "rf-calendar"
    ports:
      - "9197:9097"
      - "3007:3007"
    environment:
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK_ENV}
      - LISTEN_ADDRESS=0.0.0.0:3007
      - DB_URL=postgres://postgres:postgres@rf-crm-postgresdb/rf_calendar?sslmode=disable
      - LISTEN_ADDRESS_HTTP=0.0.0.0:9097
      - TRACE_ENABLE=false
      - DB_TRACE=true
      - LOG_QUERY=true
      - LOG_PAYLOAD=true
      - LEAD_SERVICE_ADDRESS=rf-lead:2526
      - ORDER_SERVICE_ADDRESS=rf-order:3007
    volumes:
      - "${SSH_AUTH_SOCK_VOLUME_SRC}:${SSH_AUTH_SOCK_VOLUME_DST}"
      - ${GOPATH}/src/github.com/AlphaFounders/rf-calendar:/go/src/github.com/AlphaFounders/rf-calendar
    command: /usr/local/bin/app/entrypoint.sh
    networks:
      - rproxy
    labels:
      - traefik.enable=true
      - baseURL=/calendar

  rf-presence:
    build: ./rf-presence
    container_name: "rf-presence"
    ports:
      - "9098:9098"
      - "3008:3008"
    environment:
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK_ENV}
      - LISTEN_ADDRESS=0.0.0.0:3008
      - DB_URL=postgres://postgres:postgres@rf-crm-postgresdb/rf_presence?sslmode=disable
      - LISTEN_ADDRESS_HTTP=0.0.0.0:9098
      - TRACE_ENABLE=false
      - DB_TRACE=true
      - LOG_QUERY=true
      - LOG_PAYLOAD=true
    volumes:
      - "${SSH_AUTH_SOCK_VOLUME_SRC}:${SSH_AUTH_SOCK_VOLUME_DST}"
      - ${GOPATH}/src/github.com/AlphaFounders/rf-presence:/go/src/github.com/AlphaFounders/rf-presence
    command: /usr/local/bin/app/entrypoint.sh
    networks:
      - rproxy
    labels:
      - traefik.enable=true
      - baseURL=/presence

  rf-pdfgen:
    build: ./rf-pdfgen
    container_name: "rf-pdfgen"
    ports:
      - "9099:9099"
      - "3009:3009"
    environment:
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK_ENV}
      - TEMPLATE_DIRECTORY=/templates
      - LISTEN_ADDRESS=0.0.0.0:3009
      - LISTEN_ADDRESS_HTTP=0.0.0.0:9099
      - LOG_PAYLOAD=true
      - REQUEST_TRACE=false
      - DOCUMENT_SERVICE_ADDRESS=rf-document:3004
    volumes:
      - "${SSH_AUTH_SOCK_VOLUME_SRC}:${SSH_AUTH_SOCK_VOLUME_DST}"
      - ${HOME}/.ssh/known_hosts:/root/.ssh/known_hosts
      - ${HOME}/.ssh/id_rsa:/root/.ssh/id_rsa
      - ${GOPATH}/src/github.com/AlphaFounders/rf-pdfgen:/go/src/github.com/AlphaFounders/rf-pdfgen
      - ${GOPATH}/src/github.com/AlphaFounders/rf-pdfgen/templates:/templates
    command: /usr/local/bin/app/entrypoint.sh
    networks:
      - rproxy
    labels:
      - traefik.enable=true
      - baseURL=/pdfgen

networks:
  rproxy:
    external: true
